import os
from datetime import datetime
from typing import Optional

import pandas as pd

from utils.config import PATHS, REPORT
from utils.helpers import ensure_dir, get_timestamp, save_csv
from utils.logger import get_logger, log_section

logger = get_logger(__name__)

# ─── Constants ────────────────────────────────────────────────────────────────

REPORT_DIR      = PATHS["reports_dir"]
DIVIDER_HEAVY   = "═" * 60
DIVIDER_LIGHT   = "─" * 60
DIVIDER_DOTTED  = "·" * 60


class ReportGenerator:
    """
    Generates a structured scientific-style text report from the
    final prediction results produced by ModelPipeline.

    Saves report to:  reports/space_ai_report_<timestamp>.txt
    Also returns the full report as a string for console display.

    Typical usage:
        generator = ReportGenerator(results_df, pipeline_summary)
        report    = generator.generate()
        generator.save(report)
    """

    def __init__(
        self,
        results_df      : pd.DataFrame,
        pipeline_summary: Optional[dict] = None,
    ) -> None:
        if results_df is None or results_df.empty:
            raise ValueError(
                "results_df is empty or None. "
                "Run ModelPipeline.run() before generating a report."
            )
        self._df      = results_df.copy()
        self._summary = pipeline_summary or {}
        self._report  = ""

        logger.info(
            f"ReportGenerator initialised — "
            f"{len(self._df)} planets loaded"
        )

    # ─── Public Interface ─────────────────────────────────────────────────────

    def generate(self) -> str:
        """
        Builds the full report string section by section.
        Returns the complete report as a string.
        """
        log_section(logger, "Generating Report")

        sections = [
            self._build_header(),
            self._build_dataset_overview(),
            self._build_habitability_analysis(),
            self._build_top_habitable_candidates(),
            self._build_planet_type_breakdown(),
            self._build_esi_analysis(),
            self._build_model_performance(),
            self._build_feature_summary(),
            self._build_footer(),
        ]

        self._report = "\n\n".join(sections)
        logger.info("Report generated successfully")
        return self._report

    def save(
        self,
        report  : Optional[str] = None,
        path    : Optional[str] = None,
    ) -> str:
        """
        Saves the report to a timestamped .txt file in the reports/ directory.
        Returns the path where the file was saved.
        """
        content = report or self._report
        if not content:
            raise RuntimeError(
                "No report content to save. Call generate() first."
            )

        ensure_dir(REPORT_DIR)
        filename    = f"space_ai_report_{get_timestamp()}.txt"
        output_path = path or os.path.join(REPORT_DIR, filename)

        with open(output_path, "w", encoding="utf-8") as f:
            f.write(content)

        logger.info(f"Report saved → {output_path}")
        return output_path

    def save_top_candidates_csv(self, n: int = 20) -> str:
        """
        Saves the top N most habitable planet candidates to a separate CSV.
        Sorted by prob_habitable descending.
        """
        if "prob_habitable" not in self._df.columns:
            logger.warning("prob_habitable column not found — skipping CSV export.")
            return ""

        ensure_dir(REPORT_DIR)
        top_df   = (
            self._df[self._df["habitable_predicted"] == 1]
            .sort_values("prob_habitable", ascending=False)
            .head(n)
        )
        out_path = os.path.join(REPORT_DIR, f"top_{n}_habitable_candidates.csv")
        save_csv(top_df, out_path)
        logger.info(f"Top {n} candidates CSV saved → {out_path}")
        return out_path

    # ─── Section Builders ─────────────────────────────────────────────────────

    def _build_header(self) -> str:
        title     = REPORT.get("title", "Space AI System — Exoplanet Analysis Report")
        author    = REPORT.get("author", "Space AI Team")
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        return "\n".join([
            DIVIDER_HEAVY,
            f"  {title}",
            DIVIDER_HEAVY,
            f"  Generated by  : {author}",
            f"  Generated on  : {timestamp}",
            f"  Total planets : {len(self._df):,}",
            DIVIDER_HEAVY,
        ])

    def _build_dataset_overview(self) -> str:
        lines = [
            "DATASET OVERVIEW",
            DIVIDER_LIGHT,
        ]

        total = len(self._df)
        lines.append(f"  Total planets analysed       : {total:,}")

        if "koi_teq" in self._df.columns:
            temp = self._df["koi_teq"]
            lines.append(f"  Temperature range            : {temp.min():.1f}K — {temp.max():.1f}K")
            lines.append(f"  Mean temperature             : {temp.mean():.1f}K")

        if "koi_prad" in self._df.columns:
            radius = self._df["koi_prad"]
            lines.append(f"  Radius range                 : {radius.min():.2f} — {radius.max():.2f} R_earth")
            lines.append(f"  Mean radius                  : {radius.mean():.2f} R_earth")

        if "koi_insol" in self._df.columns:
            flux = self._df["koi_insol"]
            lines.append(f"  Stellar flux range           : {flux.min():.2f} — {flux.max():.2f} S_earth")

        if "earth_similarity_index" in self._df.columns:
            esi = self._df["earth_similarity_index"]
            lines.append(f"  ESI range                    : {esi.min():.3f} — {esi.max():.3f}")
            lines.append(f"  Mean ESI                     : {esi.mean():.3f}")

        return "\n".join(lines)

    def _build_habitability_analysis(self) -> str:
        lines = [
            "HABITABILITY ANALYSIS",
            DIVIDER_LIGHT,
        ]

        if "habitable_predicted" not in self._df.columns:
            lines.append("  habitable_predicted column not found.")
            return "\n".join(lines)

        total       = len(self._df)
        hab_count   = int(self._df["habitable_predicted"].sum())
        not_hab     = total - hab_count
        hab_pct     = (hab_count / total * 100) if total > 0 else 0
        not_hab_pct = 100 - hab_pct

        lines.append(f"  Habitable planets found      : {hab_count:,}  ({hab_pct:.1f}%)")
        lines.append(f"  Non-habitable planets        : {not_hab:,}  ({not_hab_pct:.1f}%)")

        if "prob_habitable" in self._df.columns:
            hab_df = self._df[self._df["habitable_predicted"] == 1]
            if not hab_df.empty:
                mean_conf = hab_df["prob_habitable"].mean() * 100
                high_conf = (hab_df["prob_habitable"] >= 0.80).sum()
                lines.append(f"  Mean habitability confidence : {mean_conf:.1f}%")
                lines.append(f"  High confidence (>=80%)      : {high_conf:,} planets")

        if "in_habitable_zone" in self._df.columns:
            hz_count = int(self._df["in_habitable_zone"].sum())
            hz_pct   = (hz_count / total * 100) if total > 0 else 0
            lines.append(f"  Planets in habitable zone    : {hz_count:,}  ({hz_pct:.1f}%)")

        return "\n".join(lines)

    def _build_top_habitable_candidates(self, n: int = 10) -> str:
        lines = [
            f"TOP {n} HABITABLE PLANET CANDIDATES",
            DIVIDER_LIGHT,
        ]

        if "habitable_predicted" not in self._df.columns:
            lines.append("  No habitability predictions available.")
            return "\n".join(lines)

        hab_df = self._df[self._df["habitable_predicted"] == 1].copy()

        if hab_df.empty:
            lines.append("  No habitable planets found in this dataset.")
            return "\n".join(lines)

        sort_col = "prob_habitable" if "prob_habitable" in hab_df.columns else "earth_similarity_index"
        if sort_col in hab_df.columns:
            hab_df = hab_df.sort_values(sort_col, ascending=False)

        top_n = hab_df.head(n)
        lines.append(
            f"  {'Rank':<6} {'Index':<8} {'ESI':<8} "
            f"{'Temp(K)':<12} {'Flux':<10} {'Radius':<10} {'Confidence':<12}"
        )
        lines.append(f"  {DIVIDER_DOTTED}")

        for rank, (idx, row) in enumerate(top_n.iterrows(), start=1):
            esi        = f"{row['earth_similarity_index']:.3f}"  if "earth_similarity_index" in row else "N/A"
            temp       = f"{row['koi_teq']:.1f}"                 if "koi_teq"   in row else "N/A"
            flux       = f"{row['koi_insol']:.3f}"               if "koi_insol" in row else "N/A"
            radius     = f"{row['koi_prad']:.2f}"                if "koi_prad"  in row else "N/A"
            confidence = f"{row['prob_habitable']*100:.1f}%"     if "prob_habitable" in row else "N/A"

            lines.append(
                f"  {rank:<6} {str(idx):<8} {esi:<8} "
                f"{temp:<12} {flux:<10} {radius:<10} {confidence:<12}"
            )

        return "\n".join(lines)

    def _build_planet_type_breakdown(self) -> str:
        lines = [
            "PLANET TYPE BREAKDOWN",
            DIVIDER_LIGHT,
        ]

        if "planet_type_predicted" not in self._df.columns:
            lines.append("  planet_type_predicted column not found.")
            return "\n".join(lines)

        total  = len(self._df)
        counts = self._df["planet_type_predicted"].value_counts()

        for ptype, count in counts.items():
            pct = (count / total) * 100
            bar = "█" * int(pct / 2)
            lines.append(f"  {ptype:<15} : {count:>5,}  ({pct:>5.1f}%)  {bar}")

        lines.append(DIVIDER_DOTTED)

        if "habitable_predicted" in self._df.columns:
            lines.append("  Habitable planets per type:")
            for ptype in counts.index:
                type_df  = self._df[self._df["planet_type_predicted"] == ptype]
                hab_in   = int(type_df["habitable_predicted"].sum())
                type_pct = (hab_in / len(type_df) * 100) if len(type_df) > 0 else 0
                lines.append(f"    {ptype:<15} : {hab_in:>4,} habitable  ({type_pct:.1f}%)")

        return "\n".join(lines)

    def _build_esi_analysis(self) -> str:
        lines = [
            "EARTH SIMILARITY INDEX (ESI) ANALYSIS",
            DIVIDER_LIGHT,
        ]

        if "earth_similarity_index" not in self._df.columns:
            lines.append("  ESI column not found.")
            return "\n".join(lines)

        esi = self._df["earth_similarity_index"]

        buckets = [
            ("Earth-like   (ESI >= 0.80)", (esi >= 0.80).sum()),
            ("Similar      (0.60 - 0.79)", ((esi >= 0.60) & (esi < 0.80)).sum()),
            ("Moderate     (0.40 - 0.59)", ((esi >= 0.40) & (esi < 0.60)).sum()),
            ("Dissimilar   (0.20 - 0.39)", ((esi >= 0.20) & (esi < 0.40)).sum()),
            ("Very diff.   (ESI < 0.20)",  (esi < 0.20).sum()),
        ]

        total = len(self._df)
        for label, count in buckets:
            pct = (count / total * 100) if total > 0 else 0
            bar = "█" * int(pct / 2)
            lines.append(f"  {label} : {count:>5,}  ({pct:>5.1f}%)  {bar}")

        lines.append(DIVIDER_DOTTED)
        lines.append(f"  Highest ESI score : {esi.max():.4f}")
        lines.append(f"  Mean ESI score    : {esi.mean():.4f}")
        lines.append(f"  Median ESI score  : {esi.median():.4f}")

        return "\n".join(lines)

    def _build_model_performance(self) -> str:
        lines = [
            "MODEL PERFORMANCE",
            DIVIDER_LIGHT,
        ]

        eval_data = self._summary.get("evaluation", {})

        hab_eval = eval_data.get("habitability_model")
        lines.append("  Habitability KNN:")
        if hab_eval:
            lines.append(f"    Accuracy   : {hab_eval.get('accuracy', 0) * 100:.2f}%")
            lines.append(f"    Precision  : {hab_eval.get('precision', 0) * 100:.2f}%")
            lines.append(f"    Recall     : {hab_eval.get('recall', 0) * 100:.2f}%")
            lines.append(f"    F1 Score   : {hab_eval.get('f1_score', 0) * 100:.2f}%")
        else:
            lines.append("    Evaluation metrics not available.")

        lines.append("")

        type_eval = eval_data.get("planet_type_model")
        lines.append("  Planet Type KNN:")
        if type_eval:
            lines.append(f"    Accuracy            : {type_eval.get('accuracy', 0) * 100:.2f}%")
            lines.append(f"    Precision (weighted): {type_eval.get('precision', 0) * 100:.2f}%")
            lines.append(f"    Recall    (weighted): {type_eval.get('recall', 0) * 100:.2f}%")
            lines.append(f"    F1        (weighted): {type_eval.get('f1_score', 0) * 100:.2f}%")
        else:
            lines.append("    Evaluation metrics not available.")

        return "\n".join(lines)

    def _build_feature_summary(self) -> str:
        lines = [
            "ENGINEERED FEATURES USED",
            DIVIDER_LIGHT,
        ]

        preprocessing = self._summary.get("preprocessing", {})

        hab_scaler  = preprocessing.get("scaler_habitability", {})
        type_scaler = preprocessing.get("scaler_planet_type", {})

        if hab_scaler and hab_scaler.get("features"):
            lines.append("  Habitability model features:")
            for feat in hab_scaler["features"]:
                lines.append(f"    - {feat}")

        if type_scaler and type_scaler.get("features"):
            lines.append("  Planet type model features:")
            for feat in type_scaler["features"]:
                lines.append(f"    - {feat}")

        engineer = preprocessing.get("engineer", {})
        if engineer and engineer.get("engineered_features"):
            lines.append("  Derived features generated:")
            for feat in engineer["engineered_features"]:
                lines.append(f"    - {feat}")

        return "\n".join(lines)

    def _build_footer(self) -> str:
        return "\n".join([
            DIVIDER_HEAVY,
            f"  {REPORT.get('title', 'Space AI System')}",
            f"  Report complete — {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
            DIVIDER_HEAVY,
        ])